import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Meteors from "@/components/ui/meteors";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=0.8"/>
      </head>
      <body className={inter.className}>
        <div className="relative min-h-screen flex max-w-screen">
          <div className="flex-1">
            <Meteors number={200} />
            <div className="relative">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}